import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {makeRuleReviewPacket,validateRuleReviewPacket} from '../scripts/lib/rule-review-packet.mjs';
import {createAirborneSimulation} from '../src/simulation.mjs';import {initialStateFingerprint,runtimeVersions,provenance} from '../server/study-run.mjs';
test('review packet maps published evidence and simulator fallbacks explicitly',()=>{
 const p=makeRuleReviewPacket();assert.equal(validateRuleReviewPacket(p),p);const rule=id=>p.commandRules.find(r=>r.id===id);assert.deepEqual(rule('holding-speed-limit').publishedSources,['IAC_13','IAC_15','IAC_17']);assert.deepEqual(rule('holding-speed-limit').demoFallback,['GAZGE','INSTA','ULQAL']);assert.deepEqual(rule('sid-climb-gradient').publishedSources,['SID_01']);assert.deepEqual(rule('fap-altitude-floor').publishedSources,['IAC_13','IAC_15','IAC_17']);assert.deepEqual(rule('approach-clearance-mismatch').publishedSources,[]);assert.equal(p.simulationAssumptions.length,8);assert.equal(p.dataset.sourceAvailability.allMatch,true);assert.equal(p.dataset.sourceAvailability.contentAdjudication,false);assert.equal(p.dataset.sourceAvailability.files.length,10);assert.equal(p.dataset.sourceValueVerification.dataset,'LTFM-SOUTH-v2');assert.equal(p.dataset.sourceValueVerification.checks.length,10);assert.equal(p.dataset.sourceValueVerification.manualReview.length,3);assert.equal(p.dataset.sourceValueVerification.externalDomainReview,false);
 const bad=structuredClone(p);bad.commandRules[0].predicate='changed after review';assert.throws(()=>validateRuleReviewPacket(bad),/detector definitions/);const badEvidence=structuredClone(p);badEvidence.dataset.sourceValueVerification.externalDomainReview=true;assert.throws(()=>validateRuleReviewPacket(badEvidence),/dataset evidence/);
});
test('review packet CLI binds the exact packet bytes into an unapproved review template',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-review-packet-'));try{const packet=path.join(root,'packet.json'),review=path.join(root,'review.json'),repo=fileURLToPath(new URL('..',import.meta.url));const r=spawnSync(process.execPath,['--import','./scripts/offline-guard.mjs','scripts/make-rule-review-packet.mjs',packet,review],{cwd:repo,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);const hash=createHash('sha256').update(fs.readFileSync(packet)).digest('hex'),template=JSON.parse(fs.readFileSync(review));assert.equal(template.reviewPacketSha256,hash);assert.equal(template.status,'unreviewed');assert.equal(JSON.parse(r.stdout).providerCalls,0);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('single-run review attachment binds packet and review hashes without inference',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-review-attach-'));try{const repo=fileURLToPath(new URL('..',import.meta.url)),packet=path.join(root,'packet.json'),reviewPath=path.join(root,'review.json'),manifestPath=path.join(root,'manifest.json'),finalPath=path.join(root,'final.json');let r=spawnSync(process.execPath,['--import','./scripts/offline-guard.mjs','scripts/make-rule-review-packet.mjs',packet,reviewPath],{cwd:repo,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);const review=JSON.parse(fs.readFileSync(reviewPath));review.status='approved';review.reviewer={name:'Synthetic Reviewer',affiliation:'fixture',role:'software fixture',reviewedAt:'2026-09-18'};for(const row of [...review.rules,...review.simulationAssumptions]){row.decision='accepted';row.evidence=['fixture'];}fs.writeFileSync(reviewPath,JSON.stringify(review,null,2)+'\n');
  const sim=createAirborneSimulation(0,42),manifest={status:'frozen-local',executionStartPolicy:'explicit-operator-arm-v1',runId:'attach-fixture',scope:'airborne-handoff-v1',seed:42,sourceFingerprint:provenance.sourceFingerprint,versions:runtimeVersions(),requestedModel:'jev-1.13.0',initialStateSha256:await initialStateFingerprint(sim),stopping:{targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,stopForFavorableResults:false},preregistered:false,independentRuleReview:false,reviewPacketSha256:null,ruleReviewSha256:null};fs.writeFileSync(manifestPath,JSON.stringify(manifest));
  r=spawnSync(process.execPath,['--import','./scripts/offline-guard.mjs','scripts/attach-rule-review.mjs',manifestPath,packet,reviewPath,finalPath],{cwd:repo,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);const final=JSON.parse(fs.readFileSync(finalPath)),packetHash=createHash('sha256').update(fs.readFileSync(packet)).digest('hex'),reviewHash=createHash('sha256').update(fs.readFileSync(reviewPath)).digest('hex');assert.equal(final.independentRuleReview,true);assert.equal(final.reviewPacketSha256,packetHash);assert.equal(final.ruleReviewSha256,reviewHash);assert.equal(JSON.parse(r.stdout).finalized,true);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
