import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {makeStudyPlan} from '../scripts/lib/study-plan.mjs';import {gitSourceState} from '../scripts/lib/git-state.mjs';
const repo=fileURLToPath(new URL('..',import.meta.url)),git=gitSourceState(repo,{requireClean:false});
function run(args){return spawnSync(process.execPath,['--import','./scripts/offline-guard.mjs',...args],{cwd:repo,encoding:'utf8',timeout:30000});}
function prepareReview(root){const packet=path.join(root,'packet.json'),review=path.join(root,'review.json'),made=run(['scripts/make-rule-review-packet.mjs',packet,review]);assert.equal(made.status,0,made.stderr);const p=JSON.parse(fs.readFileSync(review));p.status='approved';p.reviewer={name:'Synthetic Reviewer',affiliation:'fixture',role:'software test fixture',reviewedAt:'2026-09-18'};for(const row of [...p.rules,...p.simulationAssumptions]){row.decision='accepted';row.evidence=['synthetic-fixture'];}fs.writeFileSync(review,JSON.stringify(p,null,2)+'\n');return {packet,review};}
test('frozen study batch binds every deterministic seed to plan, packet, review and initial state',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-study-batch-'));try{const plan=makeStudyPlan({planId:'batch-fixture',runCount:3,targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,researchJournalMaxBytes:67108864,gitCommit:git.commit,gitTree:git.tree}),planPath=path.join(root,'plan.json'),batch=path.join(root,'batch'),r=prepareReview(root);fs.writeFileSync(planPath,JSON.stringify(plan));
  const frozen=run(['scripts/freeze-study-batch.mjs',planPath,r.packet,r.review,batch]);assert.equal(frozen.status,0,frozen.stderr);const pre=run(['scripts/study-batch-preflight.mjs',batch]);assert.equal(pre.status,0,pre.stderr);const result=JSON.parse(pre.stdout);assert.equal(result.offlineChecksPassed,true);assert.equal(result.runCount,3);assert.deepEqual(result.runs.map(x=>x.seed),plan.runs.map(x=>x.seed));assert.match(result.reviewPacketSha256,/^[a-f0-9]{64}$/);assert.equal(result.providerCalls,0);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('batch preflight rejects tampered initial state instead of substituting another seed',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-study-tamper-'));try{const plan=makeStudyPlan({planId:'tamper-fixture',runCount:2,targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,researchJournalMaxBytes:67108864,gitCommit:git.commit,gitTree:git.tree}),planPath=path.join(root,'plan.json'),batch=path.join(root,'batch'),r=prepareReview(root);fs.writeFileSync(planPath,JSON.stringify(plan));assert.equal(run(['scripts/freeze-study-batch.mjs',planPath,r.packet,r.review,batch]).status,0);
  const initial=path.join(batch,'runs',plan.runs[0].runId+'.initial.json'),sim=JSON.parse(fs.readFileSync(initial));sim.flights[0].altitude+=1;fs.writeFileSync(initial,JSON.stringify(sim));const pre=run(['scripts/study-batch-preflight.mjs',batch]);assert.notEqual(pre.status,0);assert.match(pre.stderr,/Initial state mismatch/);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('batch freeze rejects a review whose packet hash does not match the packet bytes',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-study-review-tamper-'));try{const plan=makeStudyPlan({planId:'packet-fixture',runCount:1,targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,researchJournalMaxBytes:67108864,gitCommit:git.commit,gitTree:git.tree}),planPath=path.join(root,'plan.json'),batch=path.join(root,'batch'),r=prepareReview(root);fs.writeFileSync(planPath,JSON.stringify(plan));const review=JSON.parse(fs.readFileSync(r.review));review.reviewPacketSha256='f'.repeat(64);fs.writeFileSync(r.review,JSON.stringify(review));const frozen=run(['scripts/freeze-study-batch.mjs',planPath,r.packet,r.review,batch]);assert.notEqual(frozen.status,0);assert.match(frozen.stderr,/packet hash mismatch/);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('batch preflight recomputes initial request-envelope diagnostics',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-study-envelope-'));try{const plan=makeStudyPlan({planId:'envelope-fixture',runCount:2,targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,researchJournalMaxBytes:67108864,gitCommit:git.commit,gitTree:git.tree}),planPath=path.join(root,'plan.json'),batch=path.join(root,'batch'),r=prepareReview(root);fs.writeFileSync(planPath,JSON.stringify(plan));assert.equal(run(['scripts/freeze-study-batch.mjs',planPath,r.packet,r.review,batch]).status,0);const descriptorPath=path.join(batch,'BATCH.json'),descriptor=JSON.parse(fs.readFileSync(descriptorPath));assert.match(descriptor.initialRequestDiagnostics.measurement,/not provider tokens/);assert.ok(descriptor.initialRequestDiagnostics.runs.every(x=>x.maxEnvelopeBytes<=descriptor.initialRequestDiagnostics.requestLimitBytes));descriptor.initialRequestDiagnostics.runs[0].maxEnvelopeBytes--;fs.writeFileSync(descriptorPath,JSON.stringify(descriptor));const pre=run(['scripts/study-batch-preflight.mjs',batch]);assert.notEqual(pre.status,0);assert.match(pre.stderr,/diagnostics mismatch/);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('batch preflight rejects a changed run-order artifact',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-study-order-'));try{const plan=makeStudyPlan({planId:'order-fixture',runCount:2,targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,researchJournalMaxBytes:67108864,gitCommit:git.commit,gitTree:git.tree}),planPath=path.join(root,'plan.json'),batch=path.join(root,'batch'),r=prepareReview(root);fs.writeFileSync(planPath,JSON.stringify(plan));assert.equal(run(['scripts/freeze-study-batch.mjs',planPath,r.packet,r.review,batch]).status,0);fs.appendFileSync(path.join(batch,'RUN_ORDER.csv'),'999,wrong,1\n');const pre=run(['scripts/study-batch-preflight.mjs',batch]);assert.notEqual(pre.status,0);assert.match(pre.stderr,/Run order artifact mismatch/);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('batch preflight rejects a tampered protocol snapshot',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-study-protocol-'));try{const plan=makeStudyPlan({planId:'protocol-fixture',runCount:1,targetSimulatedSeconds:60,maxWallSeconds:600,maxTotalInputTokens:100000,researchJournalMaxBytes:67108864,gitCommit:git.commit,gitTree:git.tree}),planPath=path.join(root,'plan.json'),batch=path.join(root,'batch'),r=prepareReview(root);fs.writeFileSync(planPath,JSON.stringify(plan));assert.equal(run(['scripts/freeze-study-batch.mjs',planPath,r.packet,r.review,batch]).status,0);const descriptor=JSON.parse(fs.readFileSync(path.join(batch,'BATCH.json')));assert.equal(descriptor.protocolFiles.length,10);fs.appendFileSync(path.join(batch,'protocol','docs','methodology.md'),'tamper\n');const pre=run(['scripts/study-batch-preflight.mjs',batch]);assert.notEqual(pre.status,0);assert.match(pre.stderr,/Protocol snapshot mismatch/);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
