import './offline-guard.mjs';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {aggregateStudy} from './lib/study-aggregate.mjs';import {verifyInventory} from './lib/source-inventory.mjs';import provenance from '../server/build-provenance.mjs';
const [out,...dirs]=process.argv.slice(2);if(!out||!dirs.length)throw Error('Usage: node scripts/aggregate-study.mjs NEW_OUTPUT_DIRECTORY ANALYSIS_DIR...');const dest=path.resolve(out),partial=dest+'.partial';
for(const name of [dest,partial]){try{await fs.lstat(name);throw Error('Refusing to overwrite '+name);}catch(e){if(e.code!=='ENOENT')throw e;}}await fs.mkdir(partial);
const csv=v=>'"'+String(v??'').replaceAll('"','""')+'"';
try{verifyInventory(fileURLToPath(new URL('..',import.meta.url)),provenance);const summaries=[];for(const dir of dirs)summaries.push(JSON.parse(await fs.readFile(path.join(dir,'summary.json'),'utf8')));const result=aggregateStudy(summaries);if(result.sourceFingerprint!==provenance.sourceFingerprint)throw Error('Study aggregation requires the matching source checkout');await fs.writeFile(path.join(partial,'summary.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});
 const runKeys=Object.keys(result.runs[0]);await fs.writeFile(path.join(partial,'runs.csv'),runKeys.join(',')+'\n'+result.runs.map(r=>runKeys.map(k=>csv(r[k])).join(',')).join('\n')+'\n',{flag:'wx'});
 const rules=result.byRule.map(r=>({rule:r.id,basis:r.basis,flagged:r.flagged,eligible:r.eligible,fraction:r.fraction.value,runMedian:r.runFractionDistribution.median,runMin:r.runFractionDistribution.min,runMax:r.runFractionDistribution.max})),ruleKeys=Object.keys(rules[0]??{});await fs.writeFile(path.join(partial,'rules.csv'),ruleKeys.join(',')+'\n'+rules.map(r=>ruleKeys.map(k=>csv(r[k])).join(',')).join('\n')+'\n',{flag:'wx'});
 await fs.writeFile(path.join(partial,'COMPLETE.json'),JSON.stringify({complete:true,aggregateVersion:result.aggregateVersion,planId:result.planId,planSha256:result.planSha256,designCommitmentSha256:result.designCommitmentSha256,seedListSha256:result.seedListSha256,runCount:result.runCount,sourceFingerprint:result.sourceFingerprint},null,2)+'\n',{flag:'wx'});await fs.rename(partial,dest);console.log(JSON.stringify({complete:true,output:dest,planId:result.planId,runCount:result.runCount,providerCalls:0}));
}catch(error){await fs.writeFile(path.join(partial,'FAILED.json'),JSON.stringify({complete:false,error:error.message},null,2)+'\n').catch(()=>{});throw error;}
