import {translator,eventText} from './i18n.mjs';
import React from 'react';
import {PHASES} from './simulation.mjs';
const MODES={idle:"İzleyici yok · uyku",evaluating:"TypeSafe filo kararı",active:"AI komutları uygulanıyor",awaiting:"Sonraki karar bekleniyor",disabled:"AI bağlı değil · duraklatıldı",'budget-limit':"AI sınırı · duraklatıldı",backoff:"AI hatası · duraklatıldı"};
export default function DecisionPanel({flight,state,now,language}){
 const t=translator(language),locale=language==='en'?'en-GB':'tr-TR';
 const {ai}=state,last=ai.last,decision=state.isReplay?null:last?.decisions.find(d=>d.flight===flight.id);
 return <aside className="decision-panel"><div className="panel-title"><h2>{t("TypeSafe uçuş kontrolü")}</h2><span className={ai.configured?'connected':''}><i/>{ai.configured?t("Bağlı"):t("Bağlı değil")}</span></div>
 <div className="decision-body"><div className="controller-status"><span className={ai.mode==='evaluating'?'spinner':'status-dot'}/><strong>{t(MODES[ai.mode]||ai.mode)}</strong><small>{Math.max(0,Math.ceil((ai.nextAt-now)/1000))}{t(" sn · çağrı aralığı")}</small></div>
 {!state.isReplay&&<div className="runway-list">{state.runways.map(r=><div key={r.id}><b>{r.id}</b><span className={r.occupants.length>1?'warn':r.reserved?'occupied':'good'}>{r.occupants.length?t("Pistte: ")+r.occupants.join(', '):r.reserved?t("İzin: ")+(r.reservations||[r.reserved]).join(', '):t("Müsait")}</span><small>{r.completed}{t(" hareket")}</small></div>)}</div>}
 <div className="section-label">{t("UÇAK → ATC TELEMETRİSİ")}</div><h3>{flight.id}<span>{t(PHASES[flight.phase])}</span></h3>
 <div className="flight-metrics"><div><label>{t("HIZ")}</label><strong>{flight.speed}<small> kt IAS</small></strong></div><div><label>{t("İRTİFA")}</label><strong>{flight.altitude}<small> ft</small></strong></div><div><label>{t("YÖN")}</label><strong>{flight.heading}°</strong></div></div>
 <div className="context"><div className="context-detail"><span>{t("Dikey hız / tırmanma açısı")}</span><b>{flight.verticalRate} fpm / {flight.flightPathAngle}°</b></div><div className="context-detail"><span>{t("Konum")}</span><b>{flight.x}, {flight.y} NM</b></div>{!state.isReplay&&<div className="context-detail"><span>{t("Bekleme")}</span><b>{Math.floor(flight.wait)}{t(" sn")}</b></div>}</div>
 {!state.isReplay&&flight.pilot&&<div className="context"><div className="context-detail"><span>{t("Pilot / otopilot")}</span><b>{t(flight.pilot.phase)} {flight.pilot.fix||flight.pilot.nextFix||''}</b></div><div className="context-detail"><span>{t("Yatış / yer hızı")}</span><b>{Math.round(flight.bank||0)}° / {Math.round(flight.groundSpeed||flight.speed)} kt</b></div>{flight.pilot.unable?.length>0&&<p>{t("Pilot kısıtı: ")}{flight.pilot.unable.map(t).join(' · ')}</p>}</div>}
 {!state.isReplay&&last?.trigger?.reason==='predicted-conflict'&&<p className="fine-print">{t("Yakınlaşma tahmini nedeniyle erken TypeSafe çağrısı")}</p>}
 {!state.isReplay&&<div className="result-section"><div className="section-label">{t("ATC → UÇAK KOMUTU")}</div>{decision?<><div className="auto-decision"><strong>{decision.route}</strong><p>{decision.altitude} ft · {decision.speed} kt · {decision.rate} fpm</p><small>{t("Rota güven ölçüsü ")}{decision.confidence.toFixed(2)}{t(" · doğruluk oranı değil")}</small></div><p className="fine-print">{eventText(flight.lastCommand,language)}</p></>:<p>{t("İlk TypeSafe komutu bekleniyor.")}</p>}
 {last&&<div className="telemetry"><span>{last.aircraft}{t(" uçak / ")}{last.questions}{t(" karar")}</span><span>{last.latencyMs} ms</span><span>{last.applied}{t(" uygulandı · ")}{last.rejected}{t(" reddedildi")}</span></div>}</div>}
 <div className="experiment-metrics"><div><span>{t("Ayrım ihlali")}</span><b>{state.stats.separationEpisodes}</b></div><div><span>{t("Pist ihlali")}</span><b>{state.stats.runwayIncursions}</b></div><div><span>{t("Sektör dışı geliş")}</span><b>{state.stats.sectorViolations}</b></div><div><span>{t("Uçak-saat maruziyeti")}</span><b>{state.stats.aircraftHours.toFixed(2)}</b></div></div>
 <div className="usage-panel"><div><span>{t("Günlük AI kullanımı")}</span><b>{ai.budget.tokens.toLocaleString(locale)} / {ai.budget.limit.toLocaleString(locale)}</b></div><div className="bar"><i style={{width:Math.min(100,ai.budget.tokens/ai.budget.limit*100)+'%'}}/></div><small>{t("Giriş tokenı + belirsiz çağrı rezervi · ")}{ai.budget.requests}{t(" çağrı / saat")}</small></div>
 <section className="event-log"><h4>{t("Deney olayları")}</h4>{state.events.slice(0,12).map((e,i)=><div key={i}><time>{Math.floor(e.time/60)}:{String(e.time%60).padStart(2,'0')}</time><i className={e.source==='typesafe'?'ai-event':'local-event'}/><span>{eventText(e.text,language)}</span></div>)}</section>
 <p className="fine-print">{t("Yerel ATC yok. Pilot modeli AI talimatlarını fizik ve prosedür sınırlarıyla uygular; yakınlaşma tahmini yeni AI talimatı ister. AI beklenirken deney zamanı durur. Son izleyici ayrılınca en geç 20 saniyede uyur.")}</p>
 </div></aside>;
}
